server:
    port: 8081
    context-path: /app1
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: portal
      clientSecret: secret
      accessTokenUri: http://localhost:8080/sso-server/oauth/token
      userAuthorizationUri: http://localhost:8080/sso-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/sso-server/user/me

#  oauth2:
#    client:
#      clientId: portal
#      clientSecret: secret
#      accessTokenUri: http://localhost:9090/ecom/auth/oauth/token
#      userAuthorizationUri: http://localhost:9090/ecom/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:9090/ecom/auth/user/me

logging:
  level: debug
