server:
    port: 8082
    context-path: /app2
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: portal
      clientSecret: secret
      accessTokenUri: http://localhost:8080/sso-server/oauth/token
      userAuthorizationUri: http://localhost:8080/sso-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/sso-server/user/me
logging:
  level: debug
